### ISSUE TITLE
执行exporter-win.exe文件闪退

### ISSUE THREAD

**Issue by hpyperry** [yeziyezi/my-excel-exporter#1]
## 配置文件如下  隐私信息已经用xxx替换
```yaml
{
  "driver": "mysql",
  "username": "root",
  "password": "Test_123",
  "host": "localhost",
  "port": "3306",
  "schema": "video",
  "listSheetName":"表清单",
  "excelPath":"./result.xlsx",
  "tableColName": "表名",
  "style": {
      "hyperLinkStyle": {
        "font": {
          "underline": "single",
          "color": "#0066CC"
        }
      },
      "hyperLinkTitleStyle": {
        "font": {
          "underline": "single",
          "color": "#0066CC"
        },
        "alignment": {
          "horizontal": "center"
        }
      }
    }
}
```
